# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017-2023 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/asus_a86/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/asus_a86/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/asus/asus_a86/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/asus/asus_a86/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/asus/asus_a86/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/asus/asus_a86/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/asus/asus_a86/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/asus/asus_a86/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/asus/asus_a86/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/asus/asus_a86/proprietary/bin/radish:system/bin/radish \
    vendor/asus/asus_a86/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/asus/asus_a86/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/asus/asus_a86/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/asus/asus_a86/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/asus/asus_a86/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/asus/asus_a86/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/asus/asus_a86/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/asus/asus_a86/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/asus/asus_a86/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/asus/asus_a86/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/asus_a86/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/asus/asus_a86/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/asus/asus_a86/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    TimeService \
    qcrilmsgtunnel \
    shutdownlistener
